### ISSUE TITLE
1.6.0 Fixes

### ISSUE THREAD

**Issue by Basilakis** [easydigitaldownloads/edd-user-history#10]
/**
 * Returns the main instance of edduh.
 *
 * @since  1.6.0
 * @return WooCommerce
 */

Code has some strange things inside! o.O

**Comment by cklosowski** [comment]
Going to get this updated with the final details of the 1.6 release that includes the ownership change.

**Comment by sunnyratilal** [comment]
@cklosowski On initial activation, this error is getting generated:
![image](https://user-images.githubusercontent.com/1525554/31148838-dc8958ca-a885-11e7-8f70-a3201e337229.png)

**Comment by cklosowski** [comment]
Yeah. That's being done by the dbDelta. I think maybe we need to add a
table exists check.

**Comment by sunnyratilal** [comment]
@cklosowski loading it on `plugins_loaded`, seems to break it. Any ideas? Commit: cfe78cd31fa341417a0f1ba76597f92afe461464

**Comment by sunnyratilal** [comment]
@cklosowski no worries, fixed in 185505c2e549312f9b75d17772d4440433aebb17

**Comment by cklosowski** [comment]
@sunnyratilal I tried loading it on `plugins_loaded` as well with no avail. I say for now we can just avoid that for the 1.6 release. The rest of this looks good, cook up a PR when you are ready and we can look to merge and deploy.

**Comment by pippinsplugins** [comment]
@sunnyratilal Ignore the review I just posted. Just realized the table hasn't been released in a previous version yet so no BC concerns.

**Comment by sunnyratilal** [comment]
@cklosowski I got it working on `plugins_loaded`. The reason was because the actions were doubling up.

We were doing:
```php
add_action( 'plugins_loaded', array( $this, 'i18n' ) );
add_action( 'plugins_loaded', array( $this, 'includes' ) );
add_action( 'plugins_loaded', array( $this, 'maybe_update_plugin' ) );
```

And we were also doing `add_action( 'plugins_loaded', 'edd_user_history', 10 );`

I changed to the calls to the above methods to be called directly: https://github.com/easydigitaldownloads/edd-user-history/commit/185505c2e549312f9b75d17772d4440433aebb17#diff-0490d8c3fc794dd61fd80bb9b7ca6f5fR69

**Comment by sunnyratilal** [comment]
PR exists at #12

**Comment by sunnyratilal** [comment]
@easydigitaldownloads/core-devs could this be tested tomorrow as part of testing day please?

**Comment by pippinsplugins** [comment]
I can test tomorrow.

**Comment by pippinsplugins** [comment]
This appears to be working perfectly for me! Can't break it.
