### ISSUE TITLE
User Browsing history on View Order Details breaks down on mobile

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/edd-user-history#11]
<img width="488" alt="screen shot 2017-09-27 at 9 58 37 am" src="https://user-images.githubusercontent.com/1390124/30917649-80fabed8-a36a-11e7-8b26-6d36982d14f4.png">

**Comment by sunnyratilal** [comment]
Don't actually think we can fix this because of the way the text wraps.

E.g. the payment postmeta items metabox also overflows.

@SDavisMedia @amdrew any ideas? Could we do a combination of `word-wrap` and `text-overflow` to fix this?

**Comment by Basilakis** [comment]
An idea - if I may - those are actual data tables, so using something like
https://datatables.net/

A quick way would be to use boot strap tables and make the table have an overflow-x based on screen size. A more quick way although.

**Comment by cklosowski** [comment]
I'd really hate to bring in libraries and bootstrap just for this. @sunnyratilal can we just covert it to a WP List table style? That breaks down nicely.

**Comment by sunnyratilal** [comment]
@cklosowski great idea, will do that instead

**Comment by sunnyratilal** [comment]
PR opened at #14
