### ISSUE TITLE
If EDD is Disabled

### ISSUE THREAD

**Issue by Basilakis** [easydigitaldownloads/edd-user-history#13]
Testing the plugin, I noticed the following error. There is no check if EDD is disabled.
I Disabled the plugin and there was errors throwing around. 

I think u need to check that and cover it! :)

**Comment by pippinsplugins** [comment]
@sunnyratilal let's get this added please.

**Comment by sunnyratilal** [comment]
@pippinsplugins this was addressed in cfe78cd31fa341417a0f1ba76597f92afe461464 as part of #10
